[package]
name = "noa_runtime_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
noa_runtime = { path = "../runtime", version = "0.1.0" }
noa_debugger_tui = { path = "../debugger-tui", version = "0.1.0" }
clap = { version = "4.5.27", features = ["derive"] }
binrw = "0.14.1"
